// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHDGdI_yO9198sXYl19iwg_0yjDN5CgBE',
    appId: '1:584383597577:web:d34c130afb0c5807987cd8',
    messagingSenderId: '584383597577',
    projectId: 'spotify-clone-99dbb',
    authDomain: 'spotify-clone-99dbb.firebaseapp.com',
    storageBucket: 'spotify-clone-99dbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy2g1JK9PjYH8_0SWrgADD5UdcfjM3Ihs',
    appId: '1:584383597577:android:9acae73ef19891a8987cd8',
    messagingSenderId: '584383597577',
    projectId: 'spotify-clone-99dbb',
    storageBucket: 'spotify-clone-99dbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Q00VXpe03Sx4ig0r4SIlsM0RCf9QfZE',
    appId: '1:584383597577:ios:3953d11dac132a91987cd8',
    messagingSenderId: '584383597577',
    projectId: 'spotify-clone-99dbb',
    storageBucket: 'spotify-clone-99dbb.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHDGdI_yO9198sXYl19iwg_0yjDN5CgBE',
    appId: '1:584383597577:web:a06800bd47143f39987cd8',
    messagingSenderId: '584383597577',
    projectId: 'spotify-clone-99dbb',
    authDomain: 'spotify-clone-99dbb.firebaseapp.com',
    storageBucket: 'spotify-clone-99dbb.firebasestorage.app',
  );
}
