// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7q0H5o4nC2DzbvyFOPpHecJwh565dilY',
    appId: '1:431361482682:web:c1ea8b9ec98c8ef56c4783',
    messagingSenderId: '431361482682',
    projectId: 'spotify-clone-e604e',
    authDomain: 'spotify-clone-e604e.firebaseapp.com',
    storageBucket: 'spotify-clone-e604e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7WcNxlxFSjMQsRx4zxe7YNGWEkXQYke0',
    appId: '1:431361482682:android:faa70a8ee1ba486d6c4783',
    messagingSenderId: '431361482682',
    projectId: 'spotify-clone-e604e',
    storageBucket: 'spotify-clone-e604e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtO18gnqz0n9ymn6UJYtk2kY6V17cYjlE',
    appId: '1:431361482682:ios:220ea658bff8e6b46c4783',
    messagingSenderId: '431361482682',
    projectId: 'spotify-clone-e604e',
    storageBucket: 'spotify-clone-e604e.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7q0H5o4nC2DzbvyFOPpHecJwh565dilY',
    appId: '1:431361482682:web:797d217ef7a441fa6c4783',
    messagingSenderId: '431361482682',
    projectId: 'spotify-clone-e604e',
    authDomain: 'spotify-clone-e604e.firebaseapp.com',
    storageBucket: 'spotify-clone-e604e.firebasestorage.app',
  );
}
